<a href="https://colab.research.google.com/github/mohammedwayiz18-jpg/nlplab/blob/main/nlpexp_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tweepy
!pip install textblob
!pip install nltk
!pip install sumy

Requirement already satisfied: tweepy in /usr/local/lib/python3.12/dist-packages (4.16.0)
Requirement already satisfied: oauthlib<4,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from tweepy) (3.3.1)
Requirement already satisfied: requests<3,>=2.27.0 in /usr/local/lib/python3.12/dist-packages (from tweepy) (2.32.4)
Requirement already satisfied: requests-oauthlib<3,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from tweepy) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy) (2026.2.25)
Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Collecting sumy
  Downloading sumy-0.12.0-py3-none-any.whl.metadata (8.3 kB)
Collecting breadability>=0.1.20 (from sumy)
  Downloading breadability-0.1.20.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting docopt-ng>=0.6.1 (from sumy)
  Downloading docopt_ng-0.9.0-py3-none-any.whl.metadata (13 kB)
Collecting lxml-html-clean (from sumy)
  Downloading lxml_html_clean-0.4.4-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: nltk>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from sumy) (3.9.1)
Collecting pycountry>=18.2.23 (from sumy)
  Downloading pycountry-26.2.16-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from sumy) (2.32.4)
Requirement already satisfied: setuptools>=65.0.0 in /usr/local/lib/python3.12/dist-packages (from sumy) (75.2.0)
Collecting docopt<0.7,>=0.6.1 (from breadability>=0.1.20->sumy)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: chardet in /usr/local/lib/python3.12/dist-packages (from breadability>=0.1.20->sumy) (5.2.0)
Requirement already satisfied: lxml>=2.0 in /usr/local/lib/python3.12/dist-packages (from breadability>=0.1.20->sumy) (6.0.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.0.2->sumy) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.0.2->sumy) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.0.2->sumy) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.0.2->sumy) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.7.0->sumy) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.7.0->sumy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.7.0->sumy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.7.0->sumy) (2026.2.25)
Downloading sumy-0.12.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 3.5 MB/s eta 0:00:00
Downloading docopt_ng-0.9.0-py3-none-any.whl (16 kB)
Downloading pycountry-26.2.16-py3-none-any.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 68.3 MB/s eta 0:00:00
Downloading lxml_html_clean-0.4.4-py3-none-any.whl (14 kB)
Building wheels for collected packages: breadability, docopt
  Building wheel for breadability (setup.py) ... done
  Created wheel for breadability: filename=breadability-0.1.20-py2.py3-none-any.whl size=21695 sha256=1880fe69d5bbc8b06ff2997cc9c4538096b1a8012a613208dbf794bd8f9cd276
  Stored in directory: /root/.cache/pip/wheels/32/99/64/59305409cacd03aa03e7bddf31a9db34b1fa7033bd41972662
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=3d0592aa541242dfbfccd83ff1670b9e43947677d11475e11d4698b3cac88647
  Stored in directory: /root/.cache/pip/wheels/1a/bf/a1/4cee4f7678c68c5875ca89eaccf460593539805c3906722228
Successfully built breadability docopt
Installing collected packages: docopt, pycountry, lxml-html-clean, docopt-ng, breadability, sumy
Successfully installed breadability-0.1.20 docopt-0.6.2 docopt-ng-0.9.0 lxml-html-clean-0.4.4 pycountry-26.2.16 sumy-0.12.0

In [2]:
import pandas as pd
import numpy as np
import nltk
from textblob import TextBlob
import re

In [3]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [4]:
data = {
    "tweets":[
        "I love the new iPhone! The camera quality is amazing.",
        "This phone battery is terrible. Very disappointed.",
        "The update is okay, nothing special.",
        "Amazing performance and smooth experience.",
        "Worst phone I have ever used."
    ]
}

df = pd.DataFrame(data)
df

                                              tweets
0  I love the new iPhone! The camera quality is a...
1  This phone battery is terrible. Very disappoin...
2               The update is okay, nothing special.
3         Amazing performance and smooth experience.
4                      Worst phone I have ever used.

In [5]:
def clean_text(text):

    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"[^A-Za-z\s]", "", text)

    text = text.lower()

    return text

df["clean_tweets"] = df["tweets"].apply(clean_text)
df

,tweets,clean_tweets
0,I love the new iPhone! The camera quality is a...,i love the new iphone the camera quality is am...
1,This phone battery is terrible. Very disappoin...,this phone battery is terrible very disappointed
2,"The update is okay, nothing special.",the update is okay nothing special
3,Amazing performance and smooth experience.,amazing performance and smooth experience
4,Worst phone I have ever used.,worst phone i have ever used

In [6]:
def get_sentiment(text):

    analysis = TextBlob(text)

    if analysis.sentiment.polarity > 0:
        return "Positive"

    elif analysis.sentiment.polarity < 0:
        return "Negative"

    else:
        return "Neutral"

df["Sentiment"] = df["clean_tweets"].apply(get_sentiment)

df

,tweets,clean_tweets,Sentiment
0,I love the new iPhone! The camera quality is a...,i love the new iphone the camera quality is am...,Positive
1,This phone battery is terrible. Very disappoin...,this phone battery is terrible very disappointed,Negative
2,"The update is okay, nothing special.",the update is okay nothing special,Positive
3,Amazing performance and smooth experience.,amazing performance and smooth experience,Positive
4,Worst phone I have ever used.,worst phone i have ever used,Negative

In [7]:
df["Sentiment"].value_counts()

Sentiment
Positive    3
Negative    2
Name: count, dtype: int64

In [8]:
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer

In [10]:
import nltk
nltk.download('punkt_tab')
text = """
Artificial Intelligence is transforming the world rapidly. It is used in healthcare, education, finance,
transportation and many other industries. Machine learning and deep learning are subfields of AI that
help computers learn from data and make intelligent decisions. With the advancement of technology,
AI is expected to play a crucial role in solving complex real-world problems.
"""

parser = PlaintextParser.from_string(text, Tokenizer("english"))
summarizer = LsaSummarizer()

summary = summarizer(parser.document, 2)

for sentence in summary:
    print(sentence)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

It is used in healthcare, education, finance, transportation and many other industries.
With the advancement of technology, AI is expected to play a crucial role in solving complex real-world problems.

In [11]:
all_text = " ".join(df["clean_tweets"])

parser = PlaintextParser.from_string(all_text, Tokenizer("english"))
summarizer = LsaSummarizer()

summary = summarizer(parser.document, 2)

print("Summary of Tweets:\n")

for sentence in summary:
    print(sentence)

Summary of Tweets:

i love the new iphone the camera quality is amazing this phone battery is terrible very disappointed the update is okay nothing special amazing performance and smooth experience worst phone i have ever used